"""empty message

Revision ID: 00ca71c2a39f
Revises: 67215998dffc
Create Date: 2024-07-31 20:35:14.625614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ca71c2a39f'
down_revision = '67215998dffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')
        batch_op.drop_column('climate')

    # ### end Alembic commands ###
