"""empty message

Revision ID: 67215998dffc
Revises: 0f99599da246
Create Date: 2024-07-31 20:23:23.459544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67215998dffc'
down_revision = '0f99599da246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###
