"""empty message

Revision ID: f2e325ef35e1
Revises: f579dc7cd5bb
Create Date: 2024-07-31 14:32:31.767208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e325ef35e1'
down_revision = 'f579dc7cd5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
